"""changed category table.

Revision ID: 03fac0ff9119
Revises: 84f2050b105f
Create Date: 2024-07-23 18:42:47.899872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03fac0ff9119'
down_revision: Union[str, None] = '84f2050b105f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category_table', sa.Column('try_column', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category_table', 'try_column')
    # ### end Alembic commands ###
