"""as it was before

Revision ID: 072ac3426e2f
Revises: 228d91e8a971
Create Date: 2024-07-24 11:13:23.650727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '072ac3426e2f'
down_revision: Union[str, None] = '228d91e8a971'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category_table', 'try_column')
    op.drop_column('product_table', 'try_column')
    op.drop_column('subcategory_table', 'try_column')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subcategory_table', sa.Column('try_column', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('product_table', sa.Column('try_column', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('category_table', sa.Column('try_column', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
