"""changed subcategory and product table

Revision ID: 228d91e8a971
Revises: 583cd590e1af
Create Date: 2024-07-23 19:02:48.810886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '228d91e8a971'
down_revision: Union[str, None] = '583cd590e1af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subcategory_table', 'try_column')
    op.drop_column('product_table', 'try_column')
    op.drop_column('category_table', 'try_column')
    # ### end Alembic commands ###
