"""changed some fields in login-user table

Revision ID: 4677e70b33ae
Revises: 54bb28d212c9
Create Date: 2024-07-26 11:21:27.226874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4677e70b33ae'
down_revision: Union[str, None] = '54bb28d212c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('login_table', sa.Column('login_username', sa.String(length=200), nullable=True))
    op.drop_column('login_table', 'login_name')
    op.drop_column('user_table', 'user_email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_table', sa.Column('user_email', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('login_table', sa.Column('login_name', mysql.VARCHAR(length=200), nullable=True))
    op.drop_column('login_table', 'login_username')
    # ### end Alembic commands ###
