"""added creadted/edited by columns in some tables.

Revision ID: 5ba9e839a770
Revises: e22118d9ed89
Create Date: 2024-08-01 13:54:37.167130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ba9e839a770'
down_revision: Union[str, None] = 'e22118d9ed89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category_table', sa.Column('created_by', sa.String(length=50), nullable=False))
    op.add_column('category_table', sa.Column('edited_by', sa.String(length=50), nullable=True))
    op.add_column('product_table', sa.Column('created_by', sa.String(length=50), nullable=False))
    op.add_column('product_table', sa.Column('edited_by', sa.String(length=50), nullable=True))
    op.add_column('subcategory_table', sa.Column('created_by', sa.String(length=50), nullable=False))
    op.add_column('subcategory_table', sa.Column('edited_by', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subcategory_table', 'edited_by')
    op.drop_column('subcategory_table', 'created_by')
    op.drop_column('product_table', 'edited_by')
    op.drop_column('product_table', 'created_by')
    op.drop_column('category_table', 'edited_by')
    op.drop_column('category_table', 'created_by')
    # ### end Alembic commands ###
