"""second commit, changed something in user table

Revision ID: 7577b22729f6
Revises: c95be84527ee
Create Date: 2024-08-01 18:07:10.301089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7577b22729f6'
down_revision: Union[str, None] = 'c95be84527ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_table',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_firstname', sa.String(length=20), nullable=True),
    sa.Column('user_lastname', sa.String(length=20), nullable=True),
    sa.Column('user_gender', sa.String(length=10), nullable=True),
    sa.Column('user_address', sa.String(length=255), nullable=True),
    sa.Column('created_date', sa.String(length=50), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('user_login_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_login_id'], ['login_table.login_id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_table')
    # ### end Alembic commands ###
