"""remaking user-login tables!

Revision ID: bc2082d75984
Revises: 4677e70b33ae
Create Date: 2024-07-26 11:23:27.359823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc2082d75984'
down_revision: Union[str, None] = '4677e70b33ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_table',
    sa.Column('login_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('login_username', sa.String(length=200), nullable=True),
    sa.Column('login_password', sa.String(length=200), nullable=True),
    sa.Column('login_role', sa.String(length=20), nullable=True),
    sa.Column('login_status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('login_id')
    )
    op.create_table('user_table',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_firstname', sa.String(length=200), nullable=True),
    sa.Column('user_lastname', sa.String(length=200), nullable=True),
    sa.Column('user_gender', sa.String(length=10), nullable=True),
    sa.Column('user_address', sa.String(length=500), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_date', sa.String(length=50), nullable=True),
    sa.Column('user_login_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_login_id'], ['login_table.login_id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_table')
    op.drop_table('login_table')
    # ### end Alembic commands ###
